In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('C:\\Users\\vinod\\OneDrive\\Desktop\\DT\\PGA43_ML\\decision tree from scratch\\data\\play_tennis.csv')

In [3]:
df

    Day   Outlook Temperature Humidity    Wind PlayTennis
0    D1     Sunny         Hot     High    Weak         No
1    D2     Sunny         Hot     High  Strong         No
2    D3  Overcast         Hot     High    Weak        Yes
3    D4      Rain        Mild     High    Weak        Yes
4    D5      Rain        Cool   Normal    Weak        Yes
5    D6      Rain        Cool   Normal  Strong         No
6    D7  Overcast        Cool   Normal  Strong        Yes
7    D8     Sunny        Mild     High    Weak         No
8    D9     Sunny        Cool   Normal    Weak        Yes
9   D10      Rain        Mild   Normal    Weak        Yes
10  D11     Sunny        Mild   Normal  Strong        Yes
11  D12  Overcast        Mild     High  Strong        Yes
12  D13  Overcast         Hot   Normal    Weak        Yes
13  D14      Rain        Mild     High  Strong         No

In [5]:
df.columns

Index(['Day', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'PlayTennis'], dtype='object')

In [6]:
df['PlayTennis'].value_counts(normalize=False)

PlayTennis
Yes    9
No     5
Name: count, dtype: int64

In [7]:
def probabilities(labels):
    counts = pd.Series(labels).value_counts().to_numpy(dtype=float)
    return counts / counts.sum()

In [8]:
probabilities(df['PlayTennis'])

array([0.64285714, 0.35714286])

In [9]:
def entropy(labels):
    p = probabilities(labels)
    return float(-np.sum(p * np.log2(p)))


def gini(labels):
    p = probabilities(labels)
    return float(1 - np.sum(p ** 2))

In [10]:
entropy(df['PlayTennis']), gini(df['PlayTennis'])

(0.9402859586706311, 0.4591836734693877)

In [11]:
df['Outlook'].value_counts(normalize=False)

Outlook
Sunny       5
Rain        5
Overcast    4
Name: count, dtype: int64

In [12]:
df.groupby('Outlook')['PlayTennis'].value_counts(normalize=True)

Outlook   PlayTennis
Overcast  Yes           1.0
Rain      Yes           0.6
          No            0.4
Sunny     No            0.6
          Yes           0.4
Name: proportion, dtype: float64

In [13]:
df['Day'] = df.index + 1

In [14]:
df

    Day   Outlook Temperature Humidity    Wind PlayTennis
0     1     Sunny         Hot     High    Weak         No
1     2     Sunny         Hot     High  Strong         No
2     3  Overcast         Hot     High    Weak        Yes
3     4      Rain        Mild     High    Weak        Yes
4     5      Rain        Cool   Normal    Weak        Yes
5     6      Rain        Cool   Normal  Strong         No
6     7  Overcast        Cool   Normal  Strong        Yes
7     8     Sunny        Mild     High    Weak         No
8     9     Sunny        Cool   Normal    Weak        Yes
9    10      Rain        Mild   Normal    Weak        Yes
10   11     Sunny        Mild   Normal  Strong        Yes
11   12  Overcast        Mild     High  Strong        Yes
12   13  Overcast         Hot   Normal    Weak        Yes
13   14      Rain        Mild     High  Strong         No